version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # Topic creation via command line tool
  create-topic:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c", "sleep 10 && kafka-topics --create --topic shtootapp-events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 || true"]
  
  ozen:
    build:
      context: ./ozen
      dockerfile: Dockerfile.dev
    container_name: ozen
    environment:
      - KAFKA_BROKERS=kafka:9092
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - kafka
    volumes:
      - ./ozen:/app
