version: '3.8'

services:
  ozen-gateway:
    image: nginx:alpine
    container_name: ozen-gateway
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
